#!/usr/bin/env ruby
require 'yaml'
require 'json'
require 'uri'
require 'mechanize'

def main
  check_argv!

  id, ext = ARGV[0].split('.')
  auth = load_auth
  post_aoj(id, ext, auth)
end

def check_argv!
  return if 1 == ARGV.size

  warn "usage: ruby #{__FILE__} 0001"
  exit 1
end

def load_auth
  yaml_name = 'submit.auth.yaml'.freeze
  yaml_path = File.join(File.dirname(File.expand_path(__FILE__)),
                        yaml_name)
  YAML.load_file(yaml_path)
end

def post_aoj(id, ext, auth)
  Mechanize.new do |agent|
    header = {
      'Content-Type' => 'application/json; charset=utf-8'
    }

    json_auth = JSON.generate(auth)
    agent.post('https://judgeapi.u-aizu.ac.jp/session', json_auth, header)

    json_answer = JSON.generate(post_data_for(id, ext))
    agent.post('https://judgeapi.u-aizu.ac.jp/submissions', json_answer, header)
  end
end

LANG = {
  'c' => 'C',
  'rb' => 'Ruby'
}.freeze
def post_data_for(id, ext)
  data = {}
  data['problemId']  = id
  data['language']   = LANG[ext]
  data['sourceCode'] = load_code_for(id, ext)
  data
end

def load_code_for(id, ext)
  File.binread("#{id}.#{ext}")
end

main
